Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 80
AllCops:
  Exclude:
    - '**/sorbet'
Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'
Metrics/MethodLength:
  Max: 10
Layout/FirstHashElementIndentation:
  EnforcedStyle: 'consistent'
Layout/FirstArrayElementIndentation:
  EnforcedStyle: 'consistent'
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false