class CountryCodes
  attr_reader :country_name

  def self.country_name
    {
      AGO: "Angola",
      KIR: "Kiribati",
      GGY: "Guernsey",
      GLP: "Guadeloupe",
      COM: "Comoros",
      TCA: "Turks and Caicos Islands",
      CYM: "Cayman Islands",
      ISR: "Israel",
      SEN: "Senegal",
      SSD: "South Sudan",
      ALA: "Åland Islands",
      NZL: "New Zealand",
      PSE: "Palestine",
      LBR: "Liberia",
      SLB: "Solomon Islands",
      SVN: "Slovenia",
      TKL: "Tokelau",
      UZB: "Uzbekistan",
      ZWE: "Zimbabwe",
      TGO: "Togo",
      CAF: "Central African Republic",
      ARE: "United Arab Emirates",
      ZMB: "Zambia",
      KHM: "Cambodia",
      VNM: "Vietnam",
      PCN: "Pitcairn Islands",
      ATF: "French Southern and Antarctic Lands",
      PYF: "French Polynesia",
      ZAF: "South Africa",
      REU: "Réunion",
      AUS: "Australia",
      FIN: "Finland",
      GUY: "Guyana",
      MOZ: "Mozambique",
      TKM: "Turkmenistan",
      LAO: "Laos",
      HUN: "Hungary",
      VGB: "British Virgin Islands",
      COG: "Republic of the Congo",
      ARG: "Argentina",
      MLT: "Malta",
      TUR: "Turkey",
      HTI: "Haiti",
      GNQ: "Equatorial Guinea",
      GRC: "Greece",
      LTU: "Lithuania",
      SYR: "Syria",
      HMD: "Heard Island and McDonald Islands",
      SMR: "San Marino",
      SWE: "Sweden",
      BLZ: "Belize",
      UMI: "United States Minor Outlying Islands",
      CHL: "Chile",
      SRB: "Serbia",
      USA: "United States",
      DZA: "Algeria",
      BOL: "Bolivia",
      JEY: "Jersey",
      COK: "Cook Islands",
      VUT: "Vanuatu",
      NAM: "Namibia",
      SLV: "El Salvador",
      YEM: "Yemen",
      MAC: "Macau",
      MUS: "Mauritius",
      ABW: "Aruba",
      PRI: "Puerto Rico",
      KGZ: "Kyrgyzstan",
      GTM: "Guatemala",
      NCL: "New Caledonia",
      TON: "Tonga",
      GIN: "Guinea",
      ATA: "Antarctica",
      TTO: "Trinidad and Tobago",
      JAM: "Jamaica",
      BHS: "Bahamas",
      RUS: "Russia",
      LSO: "Lesotho",
      MMR: "Myanmar",
      BTN: "Bhutan",
      MRT: "Mauritania",
      CHN: "China",
      PRY: "Paraguay",
      GRL: "Greenland",
      FRO: "Faroe Islands",
      SJM: "Svalbard and Jan Mayen",
      GHA: "Ghana",
      MWI: "Malawi",
      PNG: "Papua New Guinea",
      FRA: "France",
      SWZ: "Eswatini",
      JOR: "Jordan",
      CAN: "Canada",
      SHN: "Saint Helena, Ascension and Tristan da Cunha",
      MAR: "Morocco",
      MNG: "Mongolia",
      NRU: "Nauru",
      ISL: "Iceland",
      LUX: "Luxembourg",
      THA: "Thailand",
      AND: "Andorra",
      BGR: "Bulgaria",
      NIC: "Nicaragua",
      ITA: "Italy",
      BLM: "Saint Barthélemy",
      ASM: "American Samoa",
      CIV: "Ivory Coast",
      PLW: "Palau",
      GUM: "Guam",
      GIB: "Gibraltar",
      AIA: "Anguilla",
      COL: "Colombia",
      TCD: "Chad",
      BRA: "Brazil",
      NPL: "Nepal",
      IMN: "Isle of Man",
      GUF: "French Guiana",
      VCT: "Saint Vincent and the Grenadines",
      PRK: "North Korea",
      SXM: "Sint Maarten",
      SUR: "Suriname",
      KWT: "Kuwait",
      SOM: "Somalia",
      TUV: "Tuvalu",
      BES: "Caribbean Netherlands",
      COD: "DR Congo",
      ALB: "Albania",
      HND: "Honduras",
      ECU: "Ecuador",
      SDN: "Sudan",
      FSM: "Micronesia",
      HKG: "Hong Kong",
      BEN: "Benin",
      ESH: "Western Sahara",
      LKA: "Sri Lanka",
      BGD: "Bangladesh",
      MDG: "Madagascar",
      BHR: "Bahrain",
      LIE: "Liechtenstein",
      MKD: "North Macedonia",
      CXR: "Christmas Island",
      UKR: "Ukraine",
      EGY: "Egypt",
      ERI: "Eritrea",
      MNP: "Northern Mariana Islands",
      AZE: "Azerbaijan",
      NER: "Niger",
      LCA: "Saint Lucia",
      MSR: "Montserrat",
      VIR: "United States Virgin Islands",
      SLE: "Sierra Leone",
      DJI: "Djibouti",
      HRV: "Croatia",
      NOR: "Norway",
      DMA: "Dominica",
      URY: "Uruguay",
      GMB: "Gambia",
      MDA: "Moldova",
      AFG: "Afghanistan",
      PRT: "Portugal",
      MNE: "Montenegro",
      BRN: "Brunei",
      FJI: "Fiji",
      MEX: "Mexico",
      CHE: "Switzerland",
      RWA: "Rwanda",
      CYP: "Cyprus",
      BMU: "Bermuda",
      TWN: "Taiwan",
      JPN: "Japan",
      QAT: "Qatar",
      DNK: "Denmark",
      CCK: "Cocos (Keeling) Islands",
      BVT: "Bouvet Island",
      BWA: "Botswana",
      MCO: "Monaco",
      LBN: "Lebanon",
      LBY: "Libya",
      MYS: "Malaysia",
      VAT: "Vatican City",
      CRI: "Costa Rica",
      ESP: "Spain",
      MTQ: "Martinique",
      SVK: "Slovakia",
      BIH: "Bosnia and Herzegovina",
      BDI: "Burundi",
      CPV: "Cape Verde",
      OMN: "Oman",
      BLR: "Belarus",
      MAF: "Saint Martin",
      BRB: "Barbados",
      UNK: "Kosovo",
      TZA: "Tanzania",
      WSM: "Samoa",
      ETH: "Ethiopia",
      IND: "India",
      EST: "Estonia",
      IRL: "Ireland",
      MDV: "Maldives",
      SYC: "Seychelles",
      UGA: "Uganda",
      FLK: "Falkland Islands",
      STP: "São Tomé and Príncipe",
      NIU: "Niue",
      TLS: "Timor-Leste",
      IRQ: "Iraq",
      KNA: "Saint Kitts and Nevis",
      CUW: "Curaçao",
      NFK: "Norfolk Island",
      MHL: "Marshall Islands",
      MLI: "Mali",
      GNB: "Guinea-Bissau",
      MYT: "Mayotte",
      POL: "Poland",
      TJK: "Tajikistan",
      GBR: "United Kingdom",
      KEN: "Kenya",
      KAZ: "Kazakhstan",
      PAN: "Panama",
      SGP: "Singapore",
      NGA: "Nigeria",
      ROU: "Romania",
      ATG: "Antigua and Barbuda",
      CZE: "Czechia",
      ARM: "Armenia",
      VEN: "Venezuela",
      PHL: "Philippines",
      WLF: "Wallis and Futuna",
      DEU: "Germany",
      PER: "Peru",
      CMR: "Cameroon",
      IOT: "British Indian Ocean Territory",
      KOR: "South Korea",
      SPM: "Saint Pierre and Miquelon",
      GAB: "Gabon",
      DOM: "Dominican Republic",
      LVA: "Latvia",
      IRN: "Iran",
      CUB: "Cuba",
      SAU: "Saudi Arabia",
      GEO: "Georgia",
      PAK: "Pakistan",
      BEL: "Belgium",
      SGS: "South Georgia",
      TUN: "Tunisia",
      NLD: "Netherlands",
      BFA: "Burkina Faso",
      IDN: "Indonesia",
      AUT: "Austria",
      GRD: "Grenada"
    }
  end
end
